### ISSUE TITLE
making a space unavailable when accepting booking

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#10]
As a space owner
So that a space doesn't get booked twice
I want the space to not be available once I confirm booking.

**Spec**
Until a user has confirmed a booking request, that space can still be booked for that night.

**Comment by missamynicholson** [comment]
1. Clicking **'Confirm booking'** would also make all the **'status'**’s of all other booking requests for that space, on that night, become **'denied'.**
   [SELECT \* FROM bookings WHERE date == date of this booking AND space_id = space_id of this booking]
   Tests!
