### ISSUE TITLE
space availability

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#5]
As a user
So that I can offer my space when is available
I want to add a range of dates to my space

**Spec**
Users should be able to offer a range of dates where their space is available.

**Comment by SergioETrillo** [comment]
We need to add to the Space model the following properties:
(in app/models/space.rb)
property :available_from, Date, required: true
property: available_to, Date, required: true

and in views/spaces/new.erb
    <input placeholder="Date inclusive" type="date" name="available_from"/>
    <input placeholder="Date inclusive" type="date" name="available to"/>

**Comment by SergioETrillo** [comment]
and in controllers/spaces.erb
change route post "/spaces" to the following, (adding available from /  to)
  post "/spaces" do
    space = Space.create(user: current_user,
                         name: params[:name],
                         description: params[:description],
                         price: params[:price], 
                         available_from: params[:available_from],
                         available_to: params[:available_to])

also the tests need to be amended to adapt to the new Space format, (add params{})
