### ISSUE TITLE
booking a space

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#6]
As a user booking a space
So that I can request for a space
I want to request a space for one night (_opt_  and get confirmation)

**Spec**
Any signed-up user can request to hire any space for one night, and this should be approved by the user that owns that space.

**Comment by missamynicholson** [comment]
1. Add a form to **/spaces** page which allows spaces to be filtered by available date. (Two input boxes and a submit button….redirects to same page) [This will probably become JQuery at some point]. Include relevant tests.
2. Add the ability to click one of the spaces on the **/spaces** page. The click should take you to a **/spaces/1** (where 1 == the space_id). This page should contain a calendar (don’t worry about the availability part at the moment). The dates in the calendar should be selectable. (At this stage, just add the ability to select one date only). Tests!
3. Add a **“Request to book”** button to the **/spaces/1** page. When clicked (make sure a date is selected first), this should create a new entry into the **Booking** database model. Tests!
4. **potential conflict with User Story 9 as both working on /bookings page**
   When the **“Request to book”** button is clicked, the **/bookings** page should open, and a “Booking requests I’ve made” section. This section should contain this new booking request.
   [SELECT \* FROM bookings WHERE user_id == my_user_id]. 
   Tests!
5. **potential conflict with User Story 7**
   Each “Booking request” in the “Booking requests I’ve Made” section should be clickable. Each one opens up a new page **/bookings/id** where id ==  booking_id
   Tests!
6. **potential conflict with B5**
   On the **/bookings/id** page show the booking info, and the space info. 
   Tests!
