### ISSUE TITLE
accepting a booking

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#7]
As a space owner
So that I can accept a booking
I want to send a confirmation

**Spec**
Any signed-up user can request to hire any space for one night, and this should be approved by the user that owns that space.

**Comment by missamynicholson** [comment]
1. **potential conflict with User Story 6**
   Each “Booking request” in the “Booking requests I’ve received” section should be clickable. Each one opens up a new page **/bookings/id** where id ==  booking_id
   Tests!
2. **potential conflict User Story 6**
   On the **bookings/id** page, show the booking info, the space info AND show other requests for this space i.e.
   [SELECT \* FROM bookings WHERE space_id == space_id for this booking.
   Tests!
3. _potential conflict User Story 6_*
   On the **bookings/id** page, if it is a booking request that I have received, add two buttons, **“Confirm booking”** or **“Deny booking”**. This should change the **‘state’** on the Booking database from ‘requested’ to either, ‘confirmed’ or ‘denied’
   Don’t forget to test ;)
