### ISSUE TITLE
booking only available spaces

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#8]
As a user
So that I don't book a space is not available
I want to be able to book only if space is available for that date

**Spec**
Nights for which a space has already been booked should not be available for users to book that space.

**Comment by missamynicholson** [comment]
1. Update the “make a booking request” system so that you can only select dates which are available (i.e. the space owner has agreed to rent out their space AND there are no other (confirmed)bookings.
   Testing!
