### ISSUE TITLE
receiving multiple requests

### ISSUE THREAD

**Issue by MariaRomero** [MariaRomero/air_bnb#9]
As a space owner
So that I receive multiple requests for one space and night
I want to receive requests until I confirm a booking

**Spec**
Until a user has confirmed a booking request, that space can still be booked for that night.

**Comment by missamynicholson** [comment]
1. Add a **/bookings** page
   Add **’status’** onto the **Booking** model (requested/confirmed/denied). Tests!
2. Add a **“Bookings”** button in the same place as the “Login/Logout” button (i.e. in one of the partials. This button directs to the **/bookings** page. Include relevant tests.
3. **potential conflict with User Story 6 as both working on /bookings page**
   Add a section called “Booking requests I’ve Received”  to the **/bookings** page which lists all the booking requests I have received (as a space owner)
   array_of_space_ids_for_spaces_I_own = [SELECT \* FROM spaces WHERE user_id == my_user_id]
   Then, [SELECT \* FROM bookings WHERE space_id is contained in array_of_space_ids_for_spaces_I_own
   *I think it’s either a LEFT JOIN or a RIGHT JOIN in SQL….http://www.w3schools.com/sql/sql_join_right.asp.  Then work out how to do this with DataMapper haha!
   Don’t forget the tests!
